@startuml
!pragma teoz true
remove  @unlinked

!include USMBase.iuml

Wijzigen1 -> W1 : RFC
W1 -> W2
W2 -> W3
W3 -> W4
W4 -> W5
W5 -> W6

W5 --> U1 : Service Request
U1 -> U2
U2 -> U3
U3 -> U4
U4 -> U5
U5 -> U6

U6 -U-> W7
W7 -> W8
W8 -> W9


@enduml