@startuml
!pragma teoz true
remove  @unlinked

!include USMBase.iuml

Verbeteren1 -> V1 : risico
V1 -> V2
V2 -> V3
V3 -> V4
V4 -> V5


V5 --> U1 : Service Request
U1 -> U2
U2 -> U3
U3 -> U4
U4 -> U5
U5 -> U6


U6 -U-> V6
V6 -> V7





@enduml