@startuml
!pragma teoz true
remove  @unlinked

!include https://raw.githubusercontent.com/vzvznl/diagrammen/main/USM/USMBase.iuml

Uitvoeren -> U1 : Service Request
U1 -> U2
U2 -> U3
U3 -> U4
U4 -> U5
U5 -> U6


@enduml