@startuml
!include https://raw.githubusercontent.com/vzvznl/diagrammen/main/include/standard.iuml

!include https://raw.githubusercontent.com/vzvznl/diagrammen/main/include/000_spelers.puml
hide unlinked

@enduml