@startuml
!$VZVZ_DONKERBLAUW = "#103A5D"
!$VZVZ_TEAL = "#00A79F"
!$VZVZ_GROEN = "#7FB95D"
!$VZVZ_ROZE = "#EC6C82"
!$VZVZ_PINK = "#E5007E"
!$VZVZ_BLAUW = "#0080C7"
!$VZVZ_TAN = "#E2DAA3"
!$VZVZ_GOLD = "#FBBE20"
!$VZVZ_SIGNAAL_ROOD = "#FF0000"
!$VZVZ_SIGNAAL_GEEL = "#FFFF00"
!$VZVZ_SIGNAAL_GROEN = "#00B050"
!$VZVZ_GRIJS_50 = "#7f7f7f"
!$VZVZ_GRIJS_35 = "#a5a5a5"
!$VZVZ_GRIJS_25 = "#bfbfbf"
!$VZVZ_GRIJS_15 = "#d8d8d8"
!$VZVZ_GRIJS_05 = "#f2f2f2"
@enduml